# no version needed since 2020

services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '4000:4000'

  update-exhibits:
    image: python
    command: bash -c "pip install -r requirements.txt && python update_exhibits.py"
    working_dir: /site/_python/
    volumes:
      - .:/site
    environment:
      - JOTFORM_API_KEY: ${JOTFORM_API_KEY}