name: Manual Build
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
        echo "Building Container"
        docker-compose build
        echo "Updating Exhibits"
        docker-compose run update-exhibits

      